### ISSUE TITLE
Not able to use expo-starter-kit with viroReact

### ISSUE THREAD

**Issue by NishthaP3** [NS-BOBBY-C/expo-starter-kit#1]
I am not able to use viroReact after cloning this repo. In package.json there isn't a package mentioned for viroReact.

**Comment by robertjcolley** [comment]
I might have developed too much further than what is shared here in this repo! I'll push something and hopefully create an official Expo Starter Kit with ViroReact.

**Comment by robertjcolley** [comment]
https://github.com/robertjcolley/expo-viro-starter-kit @NishthaP3
